config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  get 'favorites/index'
  get 'items/index'
  get 'orders/show'
  devise_for :users
  root to: 'items#index'
  resources :items do
    collection do
      get 'search'
      get 'categorize'
      get 'lists'
    end
    resources :favorites, only: %i[create destroy]
    resources :orders, only: %i[index create]
    resources :comments, only: [:create]
    resources :orders, only: %i[index create new]
  end
  resources :users, only: %i[edit update show index]
  resources :cards, only: %i[new create show destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :user_id, uniqueness: { scope: :item_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorites.includes(:user, :item).order(created_at: :desc)
    @order = Order.new
  end

  def create
    favorite = current_user.favorites.create(item_id: params[:item_id])
    redirect_to item_path(params[:item_id])
  end

  def destroy
    favorite = current_user.favorites.find_by(item_id: params[:item_id]).destroy!
    redirect_to item_path(params[:item_id])
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? && current_user.id != item.user_id && item.favorite_by?(current_user) %>
  <%= link_to item_favorite_path(item), class:"favorite-btn favorite-btn-on", method: :delete do %>
    <%= image_tag "star2.png" ,class:"favorite-star-icon favorite-star-icon-on" ,width:"20",height:"20" %>
    <span>お気に入り <%= item.favorites.count %></span>
  <% end %>
<% elsif user_signed_in? && current_user.id != item.user.id %>
  <%= link_to item_favorites_path(item), class:"favorite-btn", method: :post do %>
    <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
    <span>お気に入り <%= item.favorites.count %></span>
  <% end %> 
<% else %>
  <div class="favorite-btn">
    <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
    <span>お気に入り<%= item.favorites.count %></span>
  </div>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @item.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {item: @item}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @item.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {item: @item}) %>");

app/views/favorites/index.html.erb
<%= render "shared/second-header" %>
<div class='main'>
  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>お気に入り商品</h2>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% @favorites.each do |favorite| %>
      <li class='list'>
        <%= link_to "/items/#{favorite.item.id}" do %>
        <div class='item-img-content'>
          <% if favorite.item.images.count > 0 %>
            <%= image_tag favorite.item.images.first.variant(resize: "500x500").processed, class: "item-img" %>
            <% end %>
           <% if favorite.item.order != @order.item_id %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= favorite.item.name %>
          </h3>
          <div class='item-price'>
            <span><%= favorite.item.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= favorite.item.favorites.count %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
    </ul>
  </div>
  <%# /商品一覧 %>

</div>
<%= render "shared/second-footer" %>