config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  get 'favorites/index'
  get 'items/index'
  get 'orders/show'
  devise_for :users
  root to: 'items#index'
  resources :items do
    collection do
      get 'search'
      get 'categorize'
      get 'lists'
    end
    resources :favorites, only: %i[create destroy]
    resources :orders, only: %i[index create]
    resources :comments, only: [:create]
    resources :orders, only: %i[index create new]
  end
  resources :users, only: %i[edit update show index]
  resources :cards, only: %i[new create show destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :orders
  has_one  :card, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :nickname, presence: true
  validates :email, uniqueness: true, format: { with: /.+@.+/ }
  validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]{6,}+\z/i }

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ } do
    validates :first_name
    validates :last_name
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン]+\z/ } do
    validates :first_name_kana
    validates :last_name_kana
  end

  validates :birth_date, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: %i[edit update]

  def index
    @items = current_user.items.includes(:order, :user).order(created_at: :desc)
    @order = Order.new
  end

  def update
    if @user.update(user_params)
      sign_in(@user, bypass: true)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birth_date, :password)
  end

  def user_find
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/second-header"%>

<%# 「モデル名」にはUserモデルであれば@userを渡しましょう。「新規登録機能へのパス」は、devise導入後にrails routesを実行してdevise/registrations#createへのパスを確認し、記載してください。 %>
<%= form_with model: @user, class: 'registration-main', local: true do |f| %>
<%# //「モデル名」にはUserモデルであれば@userを渡しましょう。「新規登録機能へのパス」は、devise導入後にrails routesを実行してdevise/registrations#createへのパスを確認し、記載してください。 %>
<div class='form-wrap'>
  <div class='form-header'>
      <h1 class='form-header-text'>
        会員情報編集
      </h1>
  </div>

  <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
  <%= render 'shared/error_messages', model: f.object %>
  <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) furima太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 山田" %>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birth_date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
    <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class='register-btn register-btn-edit'>
    <%= f.submit "変更" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

<%= render "shared/second-footer"%>

app/views/users/index.html.erb
<%= render "shared/second-header" %>
<div class='main'>
  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>出品履歴</h2>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to "/items/#{item.id}" do %>
        <div class='item-img-content'>
          <% if item.images.count > 0 %>
            <%= image_tag item.images.first.variant(resize: "500x500").processed, class: "item-img" %>
            <% end %>
          <% if item.order != @order.item_id %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>

        </div>


        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
    </ul>
  </div>
  <%# /商品一覧 %>

</div>
<%= render "shared/second-footer" %>

app/views/users/show.html.erb
<%= render "shared/second-header"%>

<div class='registration-main'>
  <div class='form-wrap user-fadein'>
    <div>
        <h1 class='form-header-text-edit'>
          <%= current_user.nickname %>
        </h1>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <p class="form-text">ニックネーム</p>
        <p><%= current_user.nickname %></p>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <p class="form-text">メールアドレス</p>
        <p><%= current_user.email %></p>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <p class="form-text">お名前(全角)</p>
        <p><%= current_user.first_name %><%= current_user.last_name %></p>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <p class="form-text">お名前カナ(全角)</p>
        <p><%= current_user.first_name_kana %><%= current_user.last_name_kana %></p>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <p class="form-text">生年月日</p>
        <p><%= current_user.birth_date %></p>
      </div>
    </div>  

    <div class="register-edit">
          <ul class="register-list">
            <li>
              <%= link_to "・登録情報編集", edit_user_path(current_user), class: "register-item" %>
            </li>
            <li>
              <%= link_to "・カード情報登録", new_card_path, class: "register-item" %>
              / <%= link_to "確認", card_path(current_user), class: "register-item" %>
            </li>
          </ul>
    </div>

  </div>
 </div>
<%= render "shared/second-footer"%>