config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  get 'favorites/index'
  get 'items/index'
  get 'orders/show'
  devise_for :users
  root to: 'items#index'
  resources :items do
    collection do
      get 'search'
      get 'categorize'
      get 'lists'
    end
    resources :favorites, only: %i[create destroy]
    resources :orders, only: %i[index create]
    resources :comments, only: [:create]
    resources :orders, only: %i[index create new]
  end
  resources :users, only: %i[edit update show index]
  resources :cards, only: %i[new create show destroy]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'レディース' },
    { id: 3, name: 'メンズ' },
    { id: 4, name: 'ベビー・キッズ' },
    { id: 5, name: 'インテリア・住まい・小物' },
    { id: 6, name: '本・音楽・ゲーム' },
    { id: 7, name: 'おもちゃ・ホビー・グッズ' },
    { id: 8, name: '家電・スマホ・カメラ' },
    { id: 9, name: 'スポーツ・レジャー' },
    { id: 10, name: 'ハンドメイド' },
    { id: 11, name: 'その他' }
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :content, presence: true
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '着払い(購入者負担)' },
    { id: 3, name: '送料込み(出品者負担)' }
  ]
end

app/models/delivery_when.rb
class DeliveryWhen < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1〜2日で発送' },
    { id: 3, name: '2〜3日で発送' },
    { id: 4, name: '4〜7日で発送' }
  ]
end

app/models/delivery_where.rb
class DeliveryWhere < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: '北海道' }, {id: 3, name: '青森県'}, {id: 4, name: '岩手県'},
    {id: 5, name: '宮城県'}, {id: 6, name: '秋田県'}, {id: 7, name: '山形県'},
    {id: 8, name: '福島県'}, {id: 9, name: '茨城県'}, {id: 10, name: '栃木県'},
    {id: 11, name: '群馬県'}, {id: 12, name: '埼玉県'}, {id: 13, name: '千葉県'},
    {id: 14, name: '東京都'}, {id: 15, name: '神奈川県'}, {id: 16, name: '新潟県'},
    {id: 17, name: '富山県'}, {id: 18, name: '石川県'}, {id: 19, name: '福井県'},
    {id: 20, name: '山梨県'}, {id: 21, name: '長野県'}, {id: 22, name: '岐阜県'},
    {id: 23, name: '静岡県'}, {id: 24, name: '愛知県'}, {id: 25, name: '三重県'},
    {id: 26, name: '滋賀県'}, {id: 27, name: '京都府'}, {id: 28, name: '大阪府'},
    {id: 29, name: '兵庫県'}, {id: 30, name: '奈良県'}, {id: 31, name: '和歌山県'},
    {id: 32, name: '鳥取県'}, {id: 33, name: '島根県'}, {id: 34, name: '岡山県'},
    {id: 35, name: '広島県'}, {id: 36, name: '山口県'}, {id: 37, name: '徳島県'},
    {id: 38, name: '香川県'}, {id: 39, name: '愛媛県'}, {id: 40, name: '高知県'},
    {id: 41, name: '福岡県'}, {id: 42, name: '佐賀県'}, {id: 43, name: '長崎県'},
    {id: 44, name: '熊本県'}, {id: 45, name: '大分県'}, {id: 46, name: '宮崎県'},
    {id: 47, name: '鹿児島県'}, {id: 48, name: '沖縄県'}
  ]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :user_id, uniqueness: { scope: :item_id }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_one :order, dependent: :destroy
  has_one :card
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :status
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :delivery_when
  belongs_to_active_hash :delivery_where

  validates :name, :images, :content, :price, :category, :status, :delivery_fee, :delivery_when, :delivery_where, presence: true
  validates :category_id, :status_id, :delivery_fee_id, :delivery_when_id, :delivery_where_id, numericality: { other_than: 1, message: 'を選択してください' }
  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }

  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search != ""
      Item.where(['name LIKE(?) OR content LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Item.all
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :address
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '新品、未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :orders
  has_one  :card, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :nickname, presence: true
  validates :email, uniqueness: true, format: { with: /.+@.+/ }
  validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]{6,}+\z/i }

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ } do
    validates :first_name
    validates :last_name
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン]+\z/ } do
    validates :first_name_kana
    validates :last_name_kana
  end

  validates :birth_date, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Furima</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
        <li class="footer-link", id="footer-pull-btn">カテゴリー一覧</li>
        <div class="footer-pull-down", id="footer-pull-down">
          <ul class="footer-pull-parent">
            <li><%= link_to 'レディース', categorize_items_path(category_id: 2), class: "footer-pull-child" %></li>
            <li><%= link_to 'メンズ', categorize_items_path(category_id: 3), class: "footer-pull-child" %></li>
            <li><%= link_to 'ベビー・キッズ', categorize_items_path(category_id: 4), class: "footer-pull-child" %></li>
            <li><%= link_to 'インテリア・住まい・小物', categorize_items_path(category_id: 5), class: "footer-pull-child" %></li>
            <li><%= link_to '本・音楽・ゲーム', categorize_items_path(category_id: 6), class: "footer-pull-child" %></li>
            <li><%= link_to 'おもちゃ・ホビー・グッズ', categorize_items_path(category_id: 7), class: "footer-pull-child" %></li>
            <li><%= link_to '家電・スマホ・カメラ', categorize_items_path(category_id: 8), class: "footer-pull-child" %></li>
            <li><%= link_to 'スポーツ・レジャー', categorize_items_path(category_id: 9), class: "footer-pull-child" %></li>
            <li><%= link_to 'ハンドメイド', categorize_items_path(category_id: 10), class: "footer-pull-child" %></li>
            <li><%= link_to 'その他', categorize_items_path(category_id: 11), class: "footer-pull-child" %></li>
          </ul>
        </div>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
            <ul class="footer-list">
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
    <%= form_with(url: search_items_path, local: true, method: :get, class:"search-form") do |form| %>
      <%= form.text_field :keyword, class:'input-box', placeholder: 'キーワードから探す' %>
      <%= image_submit_tag "search.png", class:"search-button" %>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li class= "category-list", id="category-bar">カテゴリー</li>
      <ul>
        <li><%= link_to "絞り込む", "#", class: "brand-list" %></li>
        <div>
          <ul>
            <li>
            </li>
          </ul>
        </div>
      </ul>
      <div class="pull-down-none", id="pull-down">
        <ul class="pull-down">
          <li><%= link_to 'レディース', categorize_items_path(category_id: 2), class: "pull-child" %></li>
          <li><%= link_to 'メンズ', categorize_items_path(category_id: 3), class: "pull-child" %></li>
          <li><%= link_to 'ベビー・キッズ', categorize_items_path(category_id: 4), class: "pull-child" %></li>
          <li><%= link_to 'インテリア・住まい・小物', categorize_items_path(category_id: 5), class: "pull-child" %></li>
          <li><%= link_to '本・音楽・ゲーム', categorize_items_path(category_id: 6), class: "pull-child" %></li>
          <li><%= link_to 'おもちゃ・ホビー・グッズ', categorize_items_path(category_id: 7), class: "pull-child" %></li>
          <li><%= link_to '家電・スマホ・カメラ', categorize_items_path(category_id: 8), class: "pull-child" %></li>
          <li><%= link_to 'スポーツ・レジャー', categorize_items_path(category_id: 9), class: "pull-child" %></li>
          <li><%= link_to 'ハンドメイド', categorize_items_path(category_id: 10), class: "pull-child" %></li>
          <li><%= link_to 'その他', categorize_items_path(category_id: 11), class: "pull-child" %></li>
        </ul>
      </div>
    </ul>

    <% if user_signed_in? %>
      <div class="lists-right-none", id="lists-right">
      <ul class='lists-right lists-right-on'>
        <li class="list-menu"><%= link_to  "マイページ", user_path(current_user), class: "user-nickname" %></li>
        <li class="list-menu"><%= link_to  "購入履歴", orders_show_path(current_user), class: "user-nickname" %></li>
        <li class="list-menu"><%= link_to  "出品履歴", users_path(current_user), class: "user-nickname" %></li>
        <li class="list-menu"><%= link_to  "お気に入り", favorites_index_path(current_user), class: "user-nickname" %></li>
        <li class="list-logout"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      </ul>
      </div>
      <div class="icon-box", id="menu-icon">
      <h1 class="menu-btn">Menu</h1>
      </div>
    <% else %>
     <ul class='lists-right'>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      </ul>
    <% end %>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>