config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  get 'favorites/index'
  get 'items/index'
  get 'orders/show'
  devise_for :users
  root to: 'items#index'
  resources :items do
    collection do
      get 'search'
      get 'categorize'
      get 'lists'
    end
    resources :favorites, only: %i[create destroy]
    resources :orders, only: %i[index create]
    resources :comments, only: [:create]
    resources :orders, only: %i[index create new]
  end
  resources :users, only: %i[edit update show index]
  resources :cards, only: %i[new create show destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_one :order, dependent: :destroy
  has_one :card
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :status
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :delivery_when
  belongs_to_active_hash :delivery_where

  validates :name, :images, :content, :price, :category, :status, :delivery_fee, :delivery_when, :delivery_where, presence: true
  validates :category_id, :status_id, :delivery_fee_id, :delivery_when_id, :delivery_where_id, numericality: { other_than: 1, message: 'を選択してください' }
  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }

  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search != ""
      Item.where(['name LIKE(?) OR content LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Item.all
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_params, only: %i[show edit update destroy]
  before_action :sold_out, only: %i[index show search categorize lists] 

  def index
    @items = Item.includes(:user, :order).order(created_at: 'DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user).order(created_at: :desc)
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @items = Item.search(params[:keyword]).order(created_at: :desc)
  end

  def categorize
    @item = Item.where(category_id: params[:category_id]).first
    @items = Item.where(category_id: params[:category_id]).order(created_at: :desc)
  end

  def lists
    @item = Item.where(user_id: params[:user_id]).includes(:user).first
    @items = Item.where(user_id: params[:user_id]).order(created_at: :desc)
  end

  private

  def item_params
    params.require(:item).permit(:name, :content, :price, :category_id, :status_id, :delivery_fee_id, :delivery_when_id, :delivery_where_id, images: []).merge(user_id: current_user.id)
  end

  def find_params
    @item = Item.find(params[:id])
  end

  def sold_out
    @order = Order.new
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_place.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'item[images][]', id:"item-image" %>
        <div id="image-list" class='image-preview'></div>
        <% @item.images.each do |image| %>
          <% image_tag image, class: 'images' %>
        <% end %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :content, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_fee_id, DeliveryFee.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_where_id, DeliveryWhere.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_when_id, DeliveryWhen.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'>0</span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit put, class:"sell-btn" %>
      <%=link_to "戻る", root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/categorize.html.erb
<%= render "shared/second-header" %>
<div class='main'>
  <%# 商品一覧 %>
  <div class='item-contents'>
    <% if @item != nil %>
      <h2 class='title'><%= @item.category.name %>商品一覧</h2>
    <% else %>
      <h2 class='title'>出品商品がありません</h2>
    <% end %>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to "/items/#{item.id}" do %>
        <div class='item-img-content'>
          <% if item.images.count > 0 %>
            <%= image_tag item.images.first.variant(resize: "500x500").processed, class: "item-img" %>
            <% end %>
           <% if item.order != @order.item_id %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= item.favorites.count %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
    </ul>
  </div>
  <%# /商品一覧 %>

</div>
<%= render "shared/second-footer" %>

app/views/items/edit.html.erb
<%= render partial: "place", locals: { put: "変更する" } %>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          最大3%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規投稿商品', "#", class: "subtitle" %>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% @items.each do |item| %>
        <li class='list'>
          <%= link_to "items/#{item.id}" do %>
            <div class='item-img-content'>
              <% if item.images.count > 0 %>
                <%= image_tag item.images.first.variant(resize: "500x500").processed, class: "item-img" %>
              <% end %>
              <% if item.order != @order.item_id %>
              <div class='sold-out'>
                <span>Sold Out!!</span>
              </div>
              <% end %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.name %>
              </h3>
              <div class='item-price'>
                <span><%= item.price %>円<br>(税込み)</span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'><%= item.favorites.count %></span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>

      <%# 商品がない場合のダミー %>
      <%# 商品がある場合は表示されないようにしましょう %>
      <% if @item == false %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <%# //商品がある場合は表示されないようにしましょう %>
      <%# /商品がない場合のダミー %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<div class='purchase-btn'>
  <%= link_to '/items/new' do %>
  <span class='purchase-btn-text'>出品する</span>
    <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
    <% end %>
</div>
<%= render "shared/footer" %>

app/views/items/lists.html.erb
<%= render "shared/second-header" %>
<div class='main'>
  <%# 商品一覧 %>
  <div class='item-contents'>
      <h2 class='title'><%= @item.user.nickname %>さんの出品リスト</h2>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to "/items/#{item.id}" do %>
        <div class='item-img-content'>
          <% if item.images.count > 0 %>
            <%= image_tag item.images.first.variant(resize: "500x500").processed, class: "item-img" %>
            <% end %>
           <% if item.order != @order.item_id %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= item.favorites.count %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
    </ul>
  </div>
  <%# /商品一覧 %>

</div>
<%= render "shared/second-footer" %>

app/views/items/new.html.erb
<%= render partial: "place", locals: { put: "出品する" } %>

app/views/items/search.html.erb
<%= render "shared/second-header" %>
<div class='main'>
  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>検索結果</h2>
    <ul class='item-lists'>

      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to "/items/#{item.id}" do %>
        <div class='item-img-content'>
          <% if item.images.count > 0 %>
            <%= image_tag item.images.first.variant(resize: "500x500").processed, class: "item-img" %>
            <% end %>
           <% if item.order != @order.item_id %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= item.favorites.count %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
    </ul>
  </div>
  <%# /商品一覧 %>

</div>
<%= render "shared/second-footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>
<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <% @item.images.each do |image| %>
      <%= image_tag image, class:"item-box-img", style:"width: 200px; height: 200px; background-color: white;" %>
      <% end %>
      <%# 商品が売れている場合は、sold outを表示しましょう %>
      <% if @item.order != @order.item_id %>
      <div class='sold-out'>
        <span>Sold Out!!</span>
      </div>
      <% end %>
      <%# //商品が売れている場合は、sold outを表示しましょう %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= "￥#{@item.price} (税込)" %>
      </span>
      <span class="item-postage">
        <%= "#{@item.delivery_fee.name}" %>
      </span>
    </div>

    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
    <% if user_signed_in? && current_user.id == @item.user_id && @item.order == @order.item_id %>
    <%= link_to '商品の編集', "/items/#{@item.id}/edit", method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', "/items/#{@item.id}", method: :delete, class:'item-destroy' %>
    <% elsif @item.order != @order.item_id %>
    <p style="color:red; font-size:30px; font-weight: bold;"><%= "Sold Out!!" %></p>
    <%# 商品が売れていない場合はこちらを表示しましょう %>
    <% else %>
    <%= link_to '購入画面に進む', "/items/#{@item.id}/orders", class:"item-red-btn"%>
    <%= link_to '登録カードで購入', "/items/#{@item.id}/orders/new", class:"item-red-btn card-btn"%>
    <% end %>
    <%# //商品が売れていない場合はこちらを表示しましょう %>

    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <p style="font-weight:bold; font-size:20px;"><%= "商品説明" %></p>
      <p><span><%= @item.content %></span></P>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= link_to "#{@item.user.nickname}", lists_items_path(user_id: @item.user_id), class:"user-link" %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= link_to "#{@item.category.name}", categorize_items_path(category_id: @item.category_id), class:"user-link" %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.delivery_fee.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.delivery_where.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.delivery_when.name %></td>
        </tr>
      </tbody>
    </table>

    <div class="comments">
      <h1 class="comment-header">コメント一覧</h1>
        <% if @comments %>
          <div class="user-comment", id="comments">
            <% @comments.each do |comment| %>
              <h1>投稿者:<%= comment.user.nickname %>
              <p><%= comment.content %></p>
            <% end %>
          </div>
        <% end %>
    </div>

    <div class="option">
      <div class="option" id="favorites_buttons_<%= @item.id %>">
        <%= render partial: "favorites/favorite", locals: { item: @item } %>
      </div>
        <div class="report-btn">
          <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
          <span>不適切な商品の通報</span>
        </div> 
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <% if user_signed_in? && current_user.id != @item.user_id %>
      <%= form_with(model: [@item, @comment], local: true) do |form| %>
        <%= form.text_area :content, class:"comment-text" %>
        <p class="comment-warn">※相手の事を考え丁寧なコメントを心がけましょう。</p>
        <%= form.submit "コメントする", class:"comment-btn" %>
      <% end %>
    <% end %>
  </div>
  
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
</div>

<%= render "shared/footer" %>